/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IHeroiconsSolidChevronLeft: typeof import('~icons/heroicons-solid/chevron-left')['default']
    IHeroiconsSolidChevronRight: typeof import('~icons/heroicons-solid/chevron-right')['default']
    MyDialog: typeof import('./../resources/components/my-dialog.vue')['default']
    MyRadio: typeof import('./../resources/components/my-radio.vue')['default']
    MySelect: typeof import('./../resources/components/my-select.vue')['default']
    Nav: typeof import('./../resources/components/nav.vue')['default']
    NavLink: typeof import('./../resources/components/nav-link.vue')['default']
    PrimaryButton: typeof import('./../resources/components/primary-button.vue')['default']
    RouterLink: typeof import('hybridly/vue')['RouterLink']
    SecondaryButton: typeof import('./../resources/components/secondary-button.vue')['default']
  }
}
