
		/* eslint-disable */
		/* prettier-ignore */
		// This file has been automatically generated by Hybridly
		// Modifications will be discarded
		
		declare module 'hybridly' {
			export interface GlobalRouteCollection {
				url: 'https://refuel.test'
				routes: {"hybridly.action.invoke":{"uri":"invoke","wheres":[],"bindings":{}},"homepage.index":{"wheres":[],"bindings":{}},"vehicle.index":{"uri":"vehicle","wheres":[],"bindings":{}},"vehicle.show":{"uri":"vehicle/{id}","wheres":[],"bindings":{}},"vehicle.create":{"uri":"vehicle/create","wheres":[],"bindings":{}},"vehicle.destroy":{"uri":"vehicle/{id}","wheres":[],"bindings":{}}}
			}
		}
		
		export {}
	