
		/* eslint-disable */
		/* prettier-ignore */
		// This file has been automatically generated by Hybridly
		// Modifications will be discarded
		
		declare module 'hybridly' {
			export interface GlobalRouteCollection {
				url: 'https://refuel.test'
				routes: {"hybridly.action.invoke":{"uri":"invoke","wheres":[],"bindings":{}},"homepage.homepage.index":{"wheres":[],"bindings":{}}}
			}
		}
		
		export {}
	