
/* eslint-disable */
/* prettier-ignore */
// This file has been automatically generated by Hybridly
// Modifications will be discarded

import 'vue'
import type { Component, VNode, h } from 'vue'

declare module 'vue' {
	interface ComponentCustomOptions {
		properties?: Record<string, any>
		layout?: Component | Component[] | ((r: typeof h, view: VNode, dialog: VNode, properties: Record<string, any>) => VNode | VNode[])
	}
}
